# Setup
title:        CLARA
tagline:      Reactive data-stream processing framework
description:  Micro-services architecture for data analytics
baseurl:      /clara

# About/contact
author:
  name:       Vardan Gyurjyan
  email:      gurjyan@jlab.org
  url:        https://claraweb.jlab.org

# Main Docs
include:
- _downloads

exclude:
  - build
  - source
  - pubs
  - Makefile
  - README.md
  - scripts
  - Dockerfile
  - docker-compose.yml

defaults:
  - scope:
      path: docs
    values:
      layout: document

# Others
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
