# Setup
title:        CLARA
tagline:      Reactive data-stream processing framework
description:  Micro-services architecture for data analytics
baseurl:      "/clara"

# About/contact
author:
  name:       Vardan Gyurjyan
  url:        "https://claraweb.jlab.org"

# Main Docs
include: [".htaccess", "_downloads", "docs"]
exclude: ["build", "source", "pubs", "Makefile", "README.md", "scripts", "Dockerfile", "docker-compose.yml"]

# Others
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
