# Setup
title:        CLARA
tagline:      A service-oriented framework to provide a computing environment for efficient Big Data processing.
baseurl:      "/clara-docs"

# About/contact
author:
  name:       Vardan Gyurjyan
  url:        "https://JeffersonLab.github.io"

# Main Docs
include: ["_downloads", "docs"]
exclude: ["build", "source", "Makefile", "README.md", "scripts", "Dockerfile", "docker-compose.yml"]

# Others
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
