# Setup
title:        CLARA
tagline:      Distributed data-stream processing framework
description1:  Microservices architecture for big data analytics
description2:  We become what we love and who we love shapes what we become
baseurl:      "/clara-docs"

# About/contact
author:
  name:       Vardan Gyurjyan
  url:        "https://JeffersonLab.github.io"

# Main Docs
include: ["_downloads", "docs"]
exclude: ["build", "source", "pubs", "Makefile", "README.md", "scripts", "Dockerfile", "docker-compose.yml"]

# Others
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
